version: '3.9'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-dedicated-server
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    env_file:
      - default.env
    volumes:
      - ./game:/palworld
  rcon:
    image: outdead/rcon:latest
    container_name: palworld-rcon
    restart: unless-stopped
    entrypoint: ["/rcon", "-a", "172.18.0.3:25575", "-p", "ayylmao42069!"]
    tty: true
    stdin_open: true
    depends_on:
      - palworld-dedicated-server
